#!/bin/sh
FLAGS="-e __init -fno-builtin -ffreestanding -nostdlib -nodefaultlibs -nostartfiles -static -z noexecstack"
INCLUDE="./src/lib/core.o ./src/lib/lib.o"
gcc $FLAGS -o gasm ./src/gasm.c $INCLUDE